// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: LuWeiKeVideo.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30002
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30002 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

@class SMPAniImage;
@class SMPAniModel;
@class SMPAniPage;
@class SMPGraphics;
@class SMPGraphics_TouchCurves;
@class SMPImage;
@class SMPImage_Status;
@class SMPModel;
@class SMPModel_Status;
@class SMPPage;

NS_ASSUME_NONNULL_BEGIN

#pragma mark - Enum SMPConst

typedef GPB_ENUM(SMPConst) {
  SMPConst_PageMaxNumber = 10,
  SMPConst_CurveScaleBase = 10000,
  SMPConst_CurveThickStdInPageWidth = 1024,
  SMPConst_CurveThickStdInPageHeight = 768,
};

GPBEnumDescriptor *SMPConst_EnumDescriptor(void);

/**
 * Checks to see if the given value is defined by the enum or was not known at
 * the time this source was generated.
 **/
BOOL SMPConst_IsValidValue(int32_t value);

#pragma mark - Enum SMPConstCurve

typedef GPB_ENUM(SMPConstCurve) {
  SMPConstCurve_ScaleMin = 4000,
  SMPConstCurve_ScaleMax = 10000,
};

GPBEnumDescriptor *SMPConstCurve_EnumDescriptor(void);

/**
 * Checks to see if the given value is defined by the enum or was not known at
 * the time this source was generated.
 **/
BOOL SMPConstCurve_IsValidValue(int32_t value);

#pragma mark - Enum SMPGraphics_TYPE

typedef GPB_ENUM(SMPGraphics_TYPE) {
  SMPGraphics_TYPE_TtouchCurves = 0,
  SMPGraphics_TYPE_TtouchLines = 1,
};

GPBEnumDescriptor *SMPGraphics_TYPE_EnumDescriptor(void);

/**
 * Checks to see if the given value is defined by the enum or was not known at
 * the time this source was generated.
 **/
BOOL SMPGraphics_TYPE_IsValidValue(int32_t value);

#pragma mark - Enum SMPImage_ORIENTATION

typedef GPB_ENUM(SMPImage_ORIENTATION) {
  SMPImage_ORIENTATION_Up = 0,
  SMPImage_ORIENTATION_Right = 1,
  SMPImage_ORIENTATION_Down = 2,
  SMPImage_ORIENTATION_Left = 3,
};

GPBEnumDescriptor *SMPImage_ORIENTATION_EnumDescriptor(void);

/**
 * Checks to see if the given value is defined by the enum or was not known at
 * the time this source was generated.
 **/
BOOL SMPImage_ORIENTATION_IsValidValue(int32_t value);

#pragma mark - Enum SMPAniModel_TYPE

typedef GPB_ENUM(SMPAniModel_TYPE) {
  /** 显示 */
  SMPAniModel_TYPE_Show = 0,

  /** 隐藏 */
  SMPAniModel_TYPE_Hide = 1,
};

GPBEnumDescriptor *SMPAniModel_TYPE_EnumDescriptor(void);

/**
 * Checks to see if the given value is defined by the enum or was not known at
 * the time this source was generated.
 **/
BOOL SMPAniModel_TYPE_IsValidValue(int32_t value);

#pragma mark - Enum SMPAniImage_TYPE

typedef GPB_ENUM(SMPAniImage_TYPE) {
  /** 显示 */
  SMPAniImage_TYPE_Show = 0,

  /** 隐藏 */
  SMPAniImage_TYPE_Hide = 1,

  /** 改变显示顺序 */
  SMPAniImage_TYPE_Order = 2,

  /** 改变状态 */
  SMPAniImage_TYPE_Status = 3,
};

GPBEnumDescriptor *SMPAniImage_TYPE_EnumDescriptor(void);

/**
 * Checks to see if the given value is defined by the enum or was not known at
 * the time this source was generated.
 **/
BOOL SMPAniImage_TYPE_IsValidValue(int32_t value);

#pragma mark - LuWeiKeVideoRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (GPBExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c GPBExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
@interface LuWeiKeVideoRoot : GPBRootObject
@end

#pragma mark - SMPGraphics

typedef GPB_ENUM(SMPGraphics_FieldNumber) {
  SMPGraphics_FieldNumber_Type = 1,
  SMPGraphics_FieldNumber_Thickness = 2,
  SMPGraphics_FieldNumber_Color = 3,
  SMPGraphics_FieldNumber_TouchCurvesArray = 20,
};

@interface SMPGraphics : GPBMessage

@property(nonatomic, readwrite) SMPGraphics_TYPE type;

@property(nonatomic, readwrite) BOOL hasType;
@property(nonatomic, readwrite) uint32_t thickness;

@property(nonatomic, readwrite) BOOL hasThickness;
@property(nonatomic, readwrite) uint32_t color;

@property(nonatomic, readwrite) BOOL hasColor;
/** 曲线的点 */
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<SMPGraphics_TouchCurves*> *touchCurvesArray;
/** The number of items in @c touchCurvesArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger touchCurvesArray_Count;

@end

#pragma mark - SMPGraphics_TouchCurves

typedef GPB_ENUM(SMPGraphics_TouchCurves_FieldNumber) {
  SMPGraphics_TouchCurves_FieldNumber_Time = 1,
  SMPGraphics_TouchCurves_FieldNumber_X = 2,
  SMPGraphics_TouchCurves_FieldNumber_Y = 3,
  SMPGraphics_TouchCurves_FieldNumber_LineScale = 4,
};

@interface SMPGraphics_TouchCurves : GPBMessage

@property(nonatomic, readwrite) int32_t time;

@property(nonatomic, readwrite) BOOL hasTime;
@property(nonatomic, readwrite) int32_t x;

@property(nonatomic, readwrite) BOOL hasX;
@property(nonatomic, readwrite) int32_t y;

@property(nonatomic, readwrite) BOOL hasY;
@property(nonatomic, readwrite) float lineScale;

@property(nonatomic, readwrite) BOOL hasLineScale;
@end

#pragma mark - SMPModel

typedef GPB_ENUM(SMPModel_FieldNumber) {
  SMPModel_FieldNumber_GraphicsArray = 20,
};

@interface SMPModel : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<SMPGraphics*> *graphicsArray;
/** The number of items in @c graphicsArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger graphicsArray_Count;

@end

#pragma mark - SMPModel_Status

typedef GPB_ENUM(SMPModel_Status_FieldNumber) {
  SMPModel_Status_FieldNumber_X = 1,
  SMPModel_Status_FieldNumber_Y = 2,
};

@interface SMPModel_Status : GPBMessage

@property(nonatomic, readwrite) int32_t x;

@property(nonatomic, readwrite) BOOL hasX;
@property(nonatomic, readwrite) int32_t y;

@property(nonatomic, readwrite) BOOL hasY;
@end

#pragma mark - SMPImage

typedef GPB_ENUM(SMPImage_FieldNumber) {
  SMPImage_FieldNumber_ImageId = 1,
};

@interface SMPImage : GPBMessage

@property(nonatomic, readwrite) uint32_t imageId;

@property(nonatomic, readwrite) BOOL hasImageId;
@end

#pragma mark - SMPImage_Status

typedef GPB_ENUM(SMPImage_Status_FieldNumber) {
  SMPImage_Status_FieldNumber_Orientation = 1,
  SMPImage_Status_FieldNumber_X = 2,
  SMPImage_Status_FieldNumber_Y = 3,
  SMPImage_Status_FieldNumber_Scale = 4,
};

@interface SMPImage_Status : GPBMessage

@property(nonatomic, readwrite) SMPImage_ORIENTATION orientation;

@property(nonatomic, readwrite) BOOL hasOrientation;
@property(nonatomic, readwrite) int32_t x;

@property(nonatomic, readwrite) BOOL hasX;
@property(nonatomic, readwrite) int32_t y;

@property(nonatomic, readwrite) BOOL hasY;
@property(nonatomic, readwrite) float scale;

@property(nonatomic, readwrite) BOOL hasScale;
@end

#pragma mark - SMPAniModel

typedef GPB_ENUM(SMPAniModel_FieldNumber) {
  SMPAniModel_FieldNumber_Type = 1,
  SMPAniModel_FieldNumber_Time = 2,
  SMPAniModel_FieldNumber_Index = 3,
  SMPAniModel_FieldNumber_Status = 10,
};

@interface SMPAniModel : GPBMessage

@property(nonatomic, readwrite) SMPAniModel_TYPE type;

@property(nonatomic, readwrite) BOOL hasType;
@property(nonatomic, readwrite) int32_t time;

@property(nonatomic, readwrite) BOOL hasTime;
@property(nonatomic, readwrite) int32_t index;

@property(nonatomic, readwrite) BOOL hasIndex;
/** SHOW使用 */
@property(nonatomic, readwrite, strong, null_resettable) SMPModel_Status *status;
/** Test to see if @c status has been set. */
@property(nonatomic, readwrite) BOOL hasStatus;

@end

#pragma mark - SMPAniImage

typedef GPB_ENUM(SMPAniImage_FieldNumber) {
  SMPAniImage_FieldNumber_Type = 1,
  SMPAniImage_FieldNumber_Time = 2,
  SMPAniImage_FieldNumber_Index = 3,
  SMPAniImage_FieldNumber_OrderStep = 10,
  SMPAniImage_FieldNumber_Status = 20,
};

@interface SMPAniImage : GPBMessage

@property(nonatomic, readwrite) SMPAniImage_TYPE type;

@property(nonatomic, readwrite) BOOL hasType;
@property(nonatomic, readwrite) int32_t time;

@property(nonatomic, readwrite) BOOL hasTime;
@property(nonatomic, readwrite) int32_t index;

@property(nonatomic, readwrite) BOOL hasIndex;
@property(nonatomic, readwrite) int32_t orderStep;

@property(nonatomic, readwrite) BOOL hasOrderStep;
/** SHOW 和 STATUS 使用 */
@property(nonatomic, readwrite, strong, null_resettable) SMPImage_Status *status;
/** Test to see if @c status has been set. */
@property(nonatomic, readwrite) BOOL hasStatus;

@end

#pragma mark - SMPPage

typedef GPB_ENUM(SMPPage_FieldNumber) {
  SMPPage_FieldNumber_Width = 1,
  SMPPage_FieldNumber_Height = 2,
  SMPPage_FieldNumber_ImagesArray = 20,
  SMPPage_FieldNumber_ImageAnisArray = 21,
  SMPPage_FieldNumber_ModelsArray = 22,
  SMPPage_FieldNumber_ModelAnisArray = 23,
};

@interface SMPPage : GPBMessage

@property(nonatomic, readwrite) uint32_t width;

@property(nonatomic, readwrite) BOOL hasWidth;
@property(nonatomic, readwrite) uint32_t height;

@property(nonatomic, readwrite) BOOL hasHeight;
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<SMPImage*> *imagesArray;
/** The number of items in @c imagesArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger imagesArray_Count;

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<SMPAniImage*> *imageAnisArray;
/** The number of items in @c imageAnisArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger imageAnisArray_Count;

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<SMPModel*> *modelsArray;
/** The number of items in @c modelsArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger modelsArray_Count;

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<SMPAniModel*> *modelAnisArray;
/** The number of items in @c modelAnisArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger modelAnisArray_Count;

@end

#pragma mark - SMPAniPage

typedef GPB_ENUM(SMPAniPage_FieldNumber) {
  SMPAniPage_FieldNumber_Index = 1,
  SMPAniPage_FieldNumber_TimeStart = 2,
  SMPAniPage_FieldNumber_TimeEnd = 3,
};

@interface SMPAniPage : GPBMessage

@property(nonatomic, readwrite) int32_t index;

@property(nonatomic, readwrite) BOOL hasIndex;
@property(nonatomic, readwrite) int32_t timeStart;

@property(nonatomic, readwrite) BOOL hasTimeStart;
@property(nonatomic, readwrite) int32_t timeEnd;

@property(nonatomic, readwrite) BOOL hasTimeEnd;
@end

#pragma mark - SMPPackageData

typedef GPB_ENUM(SMPPackageData_FieldNumber) {
  SMPPackageData_FieldNumber_PageStartIndex = 1,
  SMPPackageData_FieldNumber_ImageIdmax = 2,
  SMPPackageData_FieldNumber_TotalTime = 3,
  SMPPackageData_FieldNumber_PagesArray = 20,
  SMPPackageData_FieldNumber_PageAnisArray = 21,
};

@interface SMPPackageData : GPBMessage

@property(nonatomic, readwrite) int32_t pageStartIndex;

@property(nonatomic, readwrite) BOOL hasPageStartIndex;
@property(nonatomic, readwrite) uint32_t imageIdmax;

@property(nonatomic, readwrite) BOOL hasImageIdmax;
/** 总时间的大概数，可能会有偏差，以具体mp3文件长度为准 */
@property(nonatomic, readwrite) int32_t totalTime;

@property(nonatomic, readwrite) BOOL hasTotalTime;
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<SMPPage*> *pagesArray;
/** The number of items in @c pagesArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger pagesArray_Count;

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<SMPAniPage*> *pageAnisArray;
/** The number of items in @c pageAnisArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger pageAnisArray_Count;

@end

#pragma mark - SMPPackageExData

typedef GPB_ENUM(SMPPackageExData_FieldNumber) {
  SMPPackageExData_FieldNumber_Uuid = 1,
  SMPPackageExData_FieldNumber_CreateTime = 2,
  SMPPackageExData_FieldNumber_Length = 3,
};

@interface SMPPackageExData : GPBMessage

/** 唯一的UUID */
@property(nonatomic, readwrite, copy, null_resettable) NSString *uuid;
/** Test to see if @c uuid has been set. */
@property(nonatomic, readwrite) BOOL hasUuid;

/** 创建时间(毫秒数) */
@property(nonatomic, readwrite) int64_t createTime;

@property(nonatomic, readwrite) BOOL hasCreateTime;
/** 课程长度(毫秒数) */
@property(nonatomic, readwrite) int32_t length;

@property(nonatomic, readwrite) BOOL hasLength;
@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
